version: 0.2

phases:
  install:
    commands:
      - echo Install phase
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      - . ~/.nvm/nvm.sh
      - nvm install 16
      - npm install -g npm@latest
      - npm install -g typescript

  pre_build:
    commands:
      - echo PREBUILD phase
      
  build:
    commands:
      - echo Build phase
      - npm run test-all

  post_build:
    commands:
      - echo POSTBUILD phase
