version: 0.2

phases:
  install:
    commands:
      - echo Install phase - nothing to install - image is complete

  pre_build:
    commands:
      - echo PREBUILD phase
      
  build:
    commands:
      - echo Build phase
      - npm install
      - npm run test-all

  post_build:
    commands:
      - echo build for production
      - npm install --omit=dev
      - echo list files 
      - ls

artifacts:
  files:
    - "dist/**/*"
    - "infrastucture/**/*"
    - "node_modules/**/*"
  name: "build-$CODEBUILD_BUILD_NUMBER"

