AWSTemplateFormatVersion:  "2010-09-09"
Description:  "Todoist lambda function to catch reminders"

Resources:
  
  LambdaExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - "lambda.amazonaws.com"
          Action:
            - "sts:AssumeRole"
      Path: "/"
      Policies:
      - PolicyName: "root"
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: "Allow"
            Action:
            - "logs:*"
            Resource: "arn:aws:logs:*:*:*"

  ReminderLambda:
    Type: "AWS::Lambda::Function"
    Properties:
      Handler: "index.lambdaHandler"
      Runtime: "nodejs18.x"
      Role: !GetAtt "LambdaExecutionRole.Arn"
      Code: "./dist/index.js"
      Tags:
        - Key: "Application"
          Value: "Todoist start date"

  ReminderLambdaURL:
    Type: "AWS::Lambda::Url"
    Properties:
      AuthType: "NONE"
      TargetFunctionArn: !GetAtt "ReminderLambda.Arn"

  ReminderLambdaUrlPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      FunctionName: !Ref "ReminderLambda"
      Action: "lambda:InvokeFunctionUrl"
      Principal: "*"
      FunctionUrlAuthType: "NONE"
      
